### ISSUE TITLE
seg fault on missing DeviceProxy_LibUSB.so

### ISSUE THREAD

**Issue by doug2000** [dominicgs/USBProxy#4]
Building newest github master on your prior BBB image resulted in:

root@arm:/home/debian/USBProxy2/USBProxy-master/src# ./usb-mitm
SIGRTMIN: 34
error opening library
Segmentation fault
root@arm:/home/debian/USBProxy2/USBProxy-master/src#

I tracked this down to a missing .so file and built it manually:

root@arm:/home/debian/USBProxy2/USBProxy-master/src/Plugins/Devices# gcc -c -fPIC DeviceProxy_LibUSB.cpp -I../../include
root@arm:/home/debian/USBProxy2/USBProxy-master/src/Plugins/Devices# gcc DeviceProxy_LibUSB.o -shared -o DeviceProxy_LibUSB.so

Then line 35 in ./lib/PluginManager.cpp from:

```
    void* DeviceProxyPlugin = dlopen(string("plugins/DeviceProxy_LibUSB.so").c_str(), RTLD_LAZY);
```

to:

```
    void* DeviceProxyPlugin = dlopen(string("Plugins/Devices/DeviceProxy_LibUSB.so").c_str(), RTLD_LAZY);
```

allowed a good start, and was able to proxy my mouse and log some output:

root@arm:/home/debian/USBProxy2/USBProxy-master/src# ./usb-mitm -l
SIGRTMIN: 34
cleaning up /tmp
removing 0
Made directory /tmp/gadget-Kf7o7c for gadget
Made directory /tmp/mqueue-G4Z8bj for mqueue
cleaning up /tmp/mqueue-G4Z8bj
removing 0
Device: 12 01 00 02 00 00 00 08 6d 04 18 c0 00 43 01 02 00 01
  Manufacturer: Logitech
  Product:      Logitech USB Optical Mouse
        *Config(1): 09 02 22 00 01 01 00 a0 32
                Interface(0):
                        *Alt(0): 09 04 00 00 01 03 01 02 00
                                HID: 09 21 11 01 00 01 22 34 00
                                EP(81): 07 05 81 03 05 00 0a
searching in [/tmp/gadget-Kf7o7c]
Starting setup writer thread (3740) for EP00.
Starting setup reader thread (3739) for EP00.
[80 06 00 03 00 00 ff 00]
[80 06 00 03 00 00 04 00]: 04 03 09 04
[80 06 02 03 09 04 ff 00]
[80 06 02 03 09 04 36 00]:
        36 03 4c 00 6f 00 67 00 69 00 74 00 65 00 63 00 68 00 20 00 55 00 53 00 42 00 20 00 4f 00 70 00
        74 00 69 00 63 00 61 00 6c 00 20 00 4d 00 6f 00 75 00 73 00 65 00
[00 09 01 00 00 00 00 00]
Opened EP81
Starting writer thread (3742) for EP81.
[21 0a 00 00 00 00 00 00]
Starting reader thread (3741) for EP81.
[81 06 00 22 00 00 74 00]
[81 06 00 22 00 00 34 00]:
        05 01 09 02 a1 01 09 01 a1 00 05 09 19 01 29 03 15 00 25 01 75 01 95 03 81 02 75 05 95 01 81 01
        05 01 09 30 09 31 09 38 15 81 25 7f 75 08 95 03 81 06 c0 c0
81[4]: 00 fd 00 00
81[4]: 00 fb ff 00
81[4]: 00 fe ff 00
81[4]: 00 01 00 00
81[4]: 00 01 00 00

**Comment by metissec** [comment]
Try installing libusb-1.0.0-dev. Worked for me.
