### ISSUE TITLE
Should USB/Proxy work on LeMaker Banana Pro?

### ISSUE THREAD

**Issue by skasync** [dominicgs/USBProxy#63]
I would like to proxy (Man-in-the-middle) with a Banana Pro ([http://wiki.lemaker.org/LeMaker_Banana_Pro/Pi](http://wiki.lemaker.org/LeMaker_Banana_Pro/Pi)), should this work ?

 usb-mitm -v .. -p ...

starts up, ep-files are created in the /tmp directory:
/tmp:
total 8
drwxrwxrwt  3 root root 4096 Feb 27 13:33 .
drwxr-xr-x 21 root root 4096 Feb 22 17:53 ..
dr-xr-xr-x  1 root root    0 Feb 27 13:33 gadget-jCgM5X

/tmp/gadget-jCgM5X:
total 4
dr-xr-xr-x 1 root root    0 Feb 27 13:33 .
drwxrwxrwt 3 root root 4096 Feb 27 13:33 ..
-rw------- 1 root root    0 Feb 27 13:33 ep1in
-rw------- 1 root root    0 Feb 27 13:33 ep1out
-rw------- 1 root root    0 Feb 27 13:33 ep2in
-rw------- 1 root root    0 Feb 27 13:33 ep2out
-rw------- 1 root root    0 Feb 27 13:33 ep3in
-rw------- 1 root root    0 Feb 27 13:33 ep3out
-rw------- 1 root root    0 Feb 27 13:33 ep4in
-rw------- 1 root root    0 Feb 27 13:33 ep4out
-rw------- 1 root root    0 Feb 27 13:33 ep5in
-rw------- 1 root root    0 Feb 27 13:33 ep5out
-rw------- 1 root root    0 Feb 27 13:33 musb-hdrc

, the device is connected:
Connected to device:  10c4:ea60@02 Silicon Labs - CP2102 USB to UART Bridge Controller

Error sending setup packet: Pipe error
Starting setup reader thread (2378) for EP00
Starting setup writer thread (2379) for EP00

 but sooner than later the machine becomes locked up and has to be reset. The USB host does not get notices about a USB device.

**Comment by dominicgs** [comment]
Could you run `lsmod` and check for any USB modules still loaded?  (perhaps paste the output here).

In general we have the best support for musb-hdrc controllers, which is what you have there, so it should hopefully be possible.
